### ISSUE TITLE
Getting asked for  a "code"

### ISSUE THREAD

**Issue by frugardc** [hkyplyr/yfantasy-api#9]
How does one configure the "code"?

```
>>> api = YahooFantasyApi(l, game)
https://api.login.yahoo.com/oauth2/request_auth?redirect_uri=oob&response_type=code&language=en-us
Enter code: 76f478fe82dcdf88c8b2de3d5dc283374a80ea04
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cfrugard/.local/lib/python3.6/site-packages/yfantasy_api/api/api.py", line 45, in __init__
    self.auth_service = AuthenticationService()
  File "/home/cfrugard/.local/lib/python3.6/site-packages/yfantasy_api/api/auth.py", line 51, in __init__
    self.__set_tokens()
  File "/home/cfrugard/.local/lib/python3.6/site-packages/yfantasy_api/api/auth.py", line 95, in __set_tokens
    self.__get_tokens()
  File "/home/cfrugard/.local/lib/python3.6/site-packages/yfantasy_api/api/auth.py", line 108, in __get_tokens
    self.__access_token = requested_tokens[ACCESS_TOKEN]
KeyError: 'access_token'
```

**Comment by hkyplyr** [comment]
In order to use this library locally, you need to create an application with Yahoo to retrieve a Client ID and Client Secret (_see [here](https://developer.yahoo.com/apps/create/)_).

Once you've obtained those values, save them as environment variables named `CLIENT_ID` and `CLIENT_SECRET` respectively. Once that's done, the url outputted above will contain your id and secret and should prompt you to login to Yahoo and then display a code for you to enter.

The whole code prompt should only be required once. The resulting access token is stored and will be automatically refreshed (with the refresh token) as needed.

**Comment by frugardc** [comment]
Excellent.  Silly clarification, but you need to go to the link manually, grab the code, then enter.  Thank you!
